server_addr: ":8765"
entity_id: "https://surf-rp.fedservice.lh"
organisation_name: "Dutch RP"
trust_anchors:
  - entity_id: "https://surfconext.fedservice.lh"
  - entity_id: "https://edugain.fedservice.lh"
authority_hints:
  - "https://surfconext.fedservice.lh"
key_storage: /data
filter_to_automatic_ops: false
enable_debug_log: false

trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
  - trust_mark_id: "https://puhuri.io"
    trust_mark_issuer: "https://puhuri.fedservice.lh"
  - trust_mark_id: "https://refeds.org/sirtfi"
    trust_mark_issuer: "https://surfconext.fedservice.lh"
