server_port: 8765
entity_id: "https://helsinki.fedservice.lh"
authority_hints:
  - "https://haka.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "Helsinki University"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
trust_marks:
  - trust_mark_id: "https://studid.io/federations/HAKA/member"
    trust_mark_issuer: "https://haka.fedservice.lh"
