services:
  edugain:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./edugain:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  erasmus-plus:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./erasmus+:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  garr:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./garr:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  haka:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./haka:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  helsinki:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./helsinki:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  incommon:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./incommon:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  puhuri:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./puhuri:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  sunet:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./sunet:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms
  surf:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./surf:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    stop_grace_period: 500ms

  surf-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./surf-rp/config.yaml:/config.yaml:ro
      - ./surf-rp:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    networks:
      caddy:
    stop_grace_period: 500ms
  puhuri-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./puhuri-rp/config.yaml:/config.yaml:ro
      - ./puhuri-rp:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    networks:
      caddy:
    stop_grace_period: 500ms
  helsinki-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./helsinki-rp/config.yaml:/config.yaml:ro
      - ./helsinki-rp:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    networks:
      caddy:
    stop_grace_period: 500ms
  garr-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./garr-rp/config.yaml:/config.yaml:ro
      - ./garr-rp:/data
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/ca.crt
    networks:
      caddy:
    stop_grace_period: 500ms


  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      caddy:
        aliases:
          - surfconext.fedservice.lh
          - edugain.fedservice.lh
          - helsinki.fedservice.lh
          - puhuri-rp.fedservice.lh
          - surf-rp.fedservice.lh
          - garr.fedservice.lh
          - erasmus-plus.fedservice.lh
          - haka.fedservice.lh
          - incommon.fedservice.lh
          - puhuri.fedservice.lh
          - sunet.fedservice.lh
          - garr-rp.fedservice.lh
          - helsinki-rp.fedservice.lh

networks:
  caddy: