services:
  edugain:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./edugain:/data
    stop_grace_period: 500ms
  erasmus-plus:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./erasmus+:/data
    stop_grace_period: 500ms
  garr:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./garr:/data
    stop_grace_period: 500ms
  haka:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./haka:/data
    stop_grace_period: 500ms
  helsinki:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./helsinki:/data
    stop_grace_period: 500ms
  incommon:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./incommon:/data
    stop_grace_period: 500ms
  puhuri:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./puhuri:/data
    stop_grace_period: 500ms
  sunet:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./sunet:/data
    stop_grace_period: 500ms
  surf:
    image: myoidc/oidfed-gota
    networks:
      caddy:
    volumes:
      - ./surf:/data
    stop_grace_period: 500ms

  surf-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./surf-rp/config.yaml:/config.yaml:ro
      - ./surf-rp:/data
    networks:
      caddy:
    stop_grace_period: 500ms
  puhuri-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./puhuri-rp/config.yaml:/config.yaml:ro
      - ./puhuri-rp:/data
    networks:
      caddy:
    stop_grace_period: 500ms
  helsinki-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./helsinki-rp/config.yaml:/config.yaml:ro
      - ./helsinki-rp:/data
    networks:
      caddy:
    stop_grace_period: 500ms
  garr-rp:
    image: myoidc/oidfed-gorp
    volumes:
      - ./garr-rp/config.yaml:/config.yaml:ro
      - ./garr-rp:/data
    networks:
      caddy:
    stop_grace_period: 500ms


  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - caddy

networks:
  caddy: