server_addr: ":4444"
entity_id: "https://goop.fedservice.lh"
organisation_name: go-oidcfed
trust_anchors:
  - entity_id: "https://trust-anchor.spid-cie.fedservice.lh/"
  - entity_id: "https://swamid.fedservice.lh/"
authority_hints:
  - "https://trust-anchor.spid-cie.fedservice.lh/"
key_storage: ./keys
filter_to_automatic_ops: false
enable_debug_log: false
use_resolve_endpoint: true
trust_marks:
  - trust_mark_id: https://tm.example.org/tm
    trust_mark_issuer: https://tm.example.org/
    min_lifetime: 60
    refresh_grace_period: 3600