server_addr: ":4444"
entity_id: "https://goop.fedservice.lh"
organisation_name: go-oidcfed
trust_anchors:
  - entity_id: "https://trust-anchor.spid-cie.fedservice.lh/"
  - entity_id: "https://swamid.fedservice.lh/"
authority_hints:
  - "https://trust-anchor.spid-cie.fedservice.lh/"
key_storage: ./keys
filter_to_automatic_ops: false
enable_debug_log: false
use_resolve_endpoint: true
trust_marks:
  - trust_mark_id: http://localhost:8765/tm
    trust_mark_issuer: http://localhost:8765/
    min_lifetime: 60
    refresh_grace_period: 3600
oidc_provider_config:
  issuer: "http://localhost:4444"
  authorization_endpoint: "http://localhost:4444/authorize"
  token_endpoint: "http://localhost:4444/token"
  userinfo_endpoint: "http://localhost:4444/userinfo"
  jwks_uri: "http://localhost:4444/.well-known/jwks.json"
  registration_endpoint: "http://localhost:4444/register"
  scopes_supported:
    - "openid"
    - "profile"
    - "email"
  response_types_supported:
    - "code"
    - "token"
    - "id_token"
  response_modes_supported:
    - "query"
    - "fragment"
  grant_types_supported:
    - "authorization_code"
  acr_values_supported:
    - "urn:mace:incommon:iap:silver"
    - "urn:mace:incommon:iap:bronze"
  subject_types_supported:
    - "public"
    - "pairwise"
