services:
  goop:
    image: myoidc/oidfed-goop
    volumes:
      - ./config.yaml:/config.yaml
      - ./keys:/keys
      - ./mkcertRootCA.pem:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
    hostname: goop.fed3
    networks:
      - default
      - traefik
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.goop-http.rule=Host("goop.fedservice.lh")
        - traefik.http.routers.goop-http.entrypoints=http
        - traefik.http.routers.goop-http.middlewares=https-redirect
        - traefik.http.routers.goop-https.rule=Host("goop.fedservice.lh")
        - traefik.http.routers.goop-https.entrypoints=https
        - traefik.http.routers.goop-https.tls=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.services.goop.loadbalancer.server.port=3333
    ports:
      - 4444:4444

networks:
  default:
  traefik:
    external: true