server_port: 8765
entity_id: "https://erasmus-plus.fedservice.lh"
authority_hints:
  - "https://edugain.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "Erasmus+"
data_location: "/data/data"
human_readable_storage: true
endpoints:
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_id: "https://erasmus-plus.ec.europa.eu"
    lifetime: 86400
    ref: "https://erasmus-plues.ec.europa.eu/ref"
    logo_uri: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Erasmus%2B_Logo.svg/799px-Erasmus%2B_Logo.svg.png"
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
