server_port: 8765
entity_id: "https://surfconext.fedservice.lh"
authority_hints:
  - "https://edugain.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "SURF.net"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_id: "https://refeds.org/sirtfi"
    lifetime: 86400
    ref: "https://refeds.org/wp-content/uploads/2022/08/Sirtfi-v2.pdf"
    delegation_jwt: %REFEDS_DELEGATION_JWT_SURFCONEXT%
    checker:
      type: none
trust_mark_owners:
  "https://refeds.org/sirtfi":
    entity_id: "https://refeds.fedservice.lh"
    jwks: %REFEDS_JWKS%
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
